Kether:
  auto-placeholder-translate: true

Workspaces:
  filter: '^(?![#!]).*\.(?i)(conf|hocon|yaml|yml|toml|json)$'
  paths:
    - 'plugins/Invero/workspace'

Database:
  # Local: SQLITE
  # External: SQL, MONGODB
  type: SQLITE
  sql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: test
    table: invero_data

Patch:
  enable-raw-title-in-vanilla-inventory: false